#Version
FROM registry.cn-shenzhen.aliyuncs.com/siguoya/xinchao-web:1.0
MAINTAINER siguoya "924714558@qq.com"
RUN apt-get install -y nginx
RUN apt-get install -y zsh
RUN apt-get install -y git
EXPOSE 80
